
spring:
  datasource:
    url: jdbc:mysql://192.168.56.102:3306/interviewtest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      max-active: 30
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.102
  application:
    name: optmistic-lock
#mybatis-plus:
#  configuration:
#    ### 开启打印sql配置
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    ### 开启驼峰配置
#    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    local-cache-scope: statement
