spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.56.102:8848
    gateway:
      routes:
        - id: order
          uri: lb://optmistic-lock
          predicates:
            - Path=/inventoryOptimisticLock/**

server:
  port: 8001
